### PR TITLE
More documentation improvements

### PR DESCRIPTION
**Pull request by xStrom**
I made some more documentation improvements so that it more accurately represents the current code.

### CODE REVIEW

**Comment by xStrom** [comment]
The methods act as defaults as well, and can be overridden. I think it's valuable information that the configuration object passed to the constructor will overwrite the values provided by the prototype.

How about:

`$.featherlight` is actually a constructor of new featherlight objects. Modify `$.featherlight.prototype` to change the default properties, or use the `configuration` object passed to the constructor to override the properties of that specific new instance.

**Comment by marcandre** [comment]
:+1: Very nicely put :smile:

If you can amend your last commit, I'll merge this PR

**Comment by xStrom** [comment]
The last commit is now changed.

**Comment by marcandre** [comment]
Awesome, thanks! :tophat:

**Pull request merged**
